---
title: "ille-et-vilaine"
author: "Chenyan Dong 163487177"
date: "30/09/2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survey)
```

```{r}
```


```{r}
## control weight of 441 estimated from population size
tuyns <- read.table("tuynsc.txt", col.names = c("case", "age", "agegp", "tobgp", "tobacco", 
                                                "logtb", "beer", "cider", 'wine', "aperitif", 
                                                "digestif", "alcohol", "logalc"))

tuyns$wt <- ifelse(tuyns$case == 1, 1, 441)
tuyns <- subset(tuyns, (tobacco != 99))

tdes <- svydesign(id = ~ 1, strata = ~ case, data = tuyns, weight = ~ wt)
```

```{r}
## Grouped data. Same original source, but now in data(esoph)
data(esoph)

unique(esoph$alcgp)

options(contrasts = c("contr.treatment","contr.treatment"))

# Expanded data
esophcase <- esoph[rep(1:88, esoph$ncases), 1:3]
esophctrl <- esoph[rep(1:88, esoph$ncontrols), 1:3]

esophcase$status <- 1
esophctrl$status <- 0

esophcase$wt <- 1
esophctrl$wt <- 441

esophlong <- rbind(esophcase, esophctrl)

des <- svydesign(id = ~ 1, weights = ~ wt, data = esophlong)
```


```{r}
grouped1s <- svyglm(status ~ agegp + alcgp + tobgp, family = binomial, design = des)
grouped1 <- glm(status ~ agegp + alcgp + tobgp, family = binomial, data = esophlong)

cont1s <- svyglm(case ~ age + I(age^2) + alcohol + tobacco, family = binomial, design = tdes)
cont1 <- glm(case ~ age + I(age^2) + alcohol + tobacco, family = binomial, data = tuyns)

grouped1s %>% summary()
grouped1 %>% summary()

as.vector(SE(cont1s))
as.vector(coef(cont1s))

cont1s %>% summary()
cont1 %>% summary()
```


```{r}
## model fitting
# group with survey design
grouped1s <- svyglm(status ~ agegp + alcgp + tobgp, family = binomial, design = des)
grouped2s <- svyglm(status ~ agegp + alcgp + tobgp + as.numeric(alcgp):as.numeric(tobgp), 
                    family = binomial, design = des)
# group
grouped1 <- glm(status ~ agegp + alcgp + tobgp, family = binomial, data = esophlong)
grouped2 <- glm(status ~ agegp + alcgp + tobgp + as.numeric(alcgp):as.numeric(tobgp), 
                family = binomial, data = esophlong)

# continue with survey design
cont1s <- svyglm(case ~ age + I(age^2) + alcohol + tobacco, family = binomial, design = tdes)
cont2s <- svyglm(case ~ age + I(age^2) + alcohol * tobacco, family = binomial, design = tdes)

# continue
cont1 <- glm(case ~ age + I(age^2) + alcohol + tobacco, family = binomial, data = tuyns)
cont2 <- glm(case ~ age + I(age^2) + alcohol * tobacco ,family = binomial, data = tuyns)


# continue with survey design 
cont3s <- svyglm(case ~ age + alcohol + tobacco, family = binomial, design = tdes)
cont4s <- svyglm(case ~ age + alcohol * tobacco, family = binomial, design = tdes)

# continue
cont3 <- glm(case ~ age + alcohol + tobacco, family = binomial, data = tuyns)
cont4 <- glm(case ~ age + alcohol * tobacco ,family = binomial, data = tuyns)
```

```{r}
grouped1s %>% summary()
grouped1 %>% summary()

grouped2s %>% summary()
grouped2 %>% summary()

cont1s %>% summary()
cont1 %>% summary()

cont2s %>% summary()
cont2 %>% summary()

cont3s %>% summary()
cont3 %>% summary()

cont4s %>% summary()
cont4 %>% summary()
```

```{r}
SE(grouped1)/SE(grouped1s)
SE(grouped2)/SE(grouped2s)

SE(cont1)/SE(cont1s)
SE(cont2)/SE(cont2s)

SE(cont3)/SE(cont3s)
SE(cont4)/SE(cont4s)
```

```{r}
par(mar = c(5.1, 4.1, 1, 1))
dotchart(c(SE(grouped1s)/SE(grouped1), NA,
           SE(cont1s)/SE(cont1))^2, pch = rep(c(1, 19), c(12, 6)), 
         xlab = "Estimated variance increase with weighting")
abline(v = 1, col = "red", lty = 3, lwd = 1.5)
```


